import os
import sys
import json
import tempfile

import numpy as np
import torch
import streamlit as st

# ─── PATH SETUP — import from src/ the same way train.py / evaluate.py do ────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR  = os.path.join(BASE_DIR, "src")
sys.path.insert(0, SRC_DIR)

from models import MODEL_REGISTRY, get_model
from preprocessing.loader import load_image
from preprocessing.pipeline import preprocess_single

# ─── CONFIG ────────────────────────────────────────────────────────────────
MODELS_DIR   = os.path.join(BASE_DIR, "outputs", "models")
METRICS_FILE = os.path.join(BASE_DIR, "outputs", "metrics", "all_metrics.json")
METRIC_KEYS  = ["Dice Score", "IoU", "Sensitivity", "Specificity", "F1 Score"]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

st.set_page_config(page_title="HemoStroke-AI", page_icon="🧠", layout="wide")


# ─── CACHED LOADERS ────────────────────────────────────────────────────────
@st.cache_resource(show_spinner=False)
def load_trained_model(model_name):
    """Load a model's weights from outputs/models/. Cached per model_name."""
    model_file = os.path.join(
        MODELS_DIR, f"{model_name.replace(' ', '_').lower()}.pth"
    )
    if not os.path.exists(model_file):
        return None, model_file
    model = get_model(model_name).to(device)
    model.load_state_dict(torch.load(model_file, map_location=device))
    model.eval()
    return model, model_file


@st.cache_data(show_spinner=False)
def load_all_metrics():
    """Load precomputed test-set metrics generated by src/evaluate.py."""
    if os.path.exists(METRICS_FILE):
        with open(METRICS_FILE) as f:
            return json.load(f)
    return None


def preprocess_for_model(raw_image):
    """
    Run the same pipeline used to build the training set (resize -> minmax
    normalize -> gaussian denoise -> contour skull-strip), then apply the
    same uint8 quantization + Normalize(0.5, 0.5) that dataset.py applies
    at training time, so inference matches training exactly.
    """
    processed = preprocess_single(
        raw_image,
        target_size=(256, 256),
        norm_method="minmax",
        noise_method="gaussian",
        skull_method="contour",
    )
    processed_uint8 = (processed * 255).clip(0, 255).astype(np.uint8)

    tensor = torch.from_numpy(processed_uint8.astype(np.float32) / 255.0)
    tensor = (tensor - 0.5) / 0.5
    tensor = tensor.unsqueeze(0).unsqueeze(0)  # (1, 1, H, W)
    return processed_uint8, tensor


def save_upload_to_temp(uploaded_file):
    """Write the uploaded file to disk with the right suffix so loader.py
    can auto-detect format (.png/.dcm/.nii/.nii.gz)."""
    name = uploaded_file.name.lower()
    if name.endswith(".nii.gz"):
        suffix = ".nii.gz"
    elif "." in name:
        suffix = "." + name.rsplit(".", 1)[1]
    else:
        suffix = ""
    with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
        tmp.write(uploaded_file.read())
        return tmp.name


# ─── SIDEBAR ───────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Settings")
    model_name = st.selectbox(
        "Model", list(MODEL_REGISTRY.keys()), index=1  # default: CNN Deep
    )
    threshold = st.slider("Stroke decision threshold", 0.0, 1.0, 0.5, 0.05)

# ─── MAIN ──────────────────────────────────────────────────────────────────
st.title("🧠 HemoStroke-AI")
st.caption("Ischemic stroke detection from brain CT scans — Normal vs Stroke")

uploaded_file = st.file_uploader(
    "Upload a CT scan (PNG, DICOM, or NIfTI)",
    type=["png", "jpg", "jpeg", "dcm", "nii", "gz"],
)

if uploaded_file is None:
    st.info("Upload a .png, .dcm, or .nii/.nii.gz CT scan to get a prediction.")
    st.stop()

tmp_path = save_upload_to_temp(uploaded_file)
try:
    raw_image = load_image(tmp_path)
except Exception as e:
    st.error(f"Could not read this file: {e}")
    os.unlink(tmp_path)
    st.stop()
os.unlink(tmp_path)

processed_uint8, tensor = preprocess_for_model(raw_image)

col1, col2 = st.columns(2)

with col1:
    st.subheader("Preprocessed scan")
    st.image(processed_uint8, clamp=True, use_container_width=True)
    st.caption("After resize \u2192 normalize \u2192 denoise \u2192 skull strip")

model, model_file = load_trained_model(model_name)

with col2:
    st.subheader("Prediction")
    if model is None:
        st.error(
            f"Model weights not found at `{os.path.relpath(model_file, BASE_DIR)}`. "
            "Copy the trained .pth file from Google Drive into outputs/models/."
        )
    else:
        with torch.no_grad():
            prob = model(tensor.to(device)).item()
        label = "Stroke" if prob >= threshold else "Normal"

        st.metric("Prediction", label)
        st.metric("Stroke probability", f"{prob:.2%}")
        st.progress(min(max(prob, 0.0), 1.0))

st.divider()

# ─── EVALUATION METRICS ────────────────────────────────────────────────────
st.subheader(f"{model_name} — test-set evaluation metrics")
all_metrics = load_all_metrics()

if all_metrics and model_name in all_metrics:
    m = all_metrics[model_name]
    cols = st.columns(5)
    for c, key in zip(cols, METRIC_KEYS):
        c.metric(key, f"{m[key]:.4f}")
    st.caption(f"Accuracy: {m['accuracy']:.2f}%")
else:
    st.info(
        "No saved metrics found. Run `python src/evaluate.py` once (where your "
        "data/processed/png and outputs/models/ are available) to generate "
        "outputs/metrics/all_metrics.json, then copy that file next to app.py."
    )
